var mongoose = require("mongoose");

var dataSchema = new mongoose.Schema({
  loanamount: String,
  firstname: String,
  lastname: String,
  phone: String,
  cellphone: String,
  email: String,
  contacttime: String,
  address: String,
  zip: String,
  city: String,
  state: String,
  fullstate: String,
  dd: String,
  mm: String,
  yyyy: String,
  military: String,
  owners: String,
  yearsatres: String,
  monthsatres: String,
  payperiod: String,
  incometype: String,
  dlstate: String,
  licensenumber: String,
  ssn: String,
  employer: String,
  jobtitle: String,
  workphone: String,
  monthsemployed: String,
  nextpaydate: String,
  followingpay: String,
  bankname: String,
  bankphone: String,
  accountnumber: String,
  routingnumber: String,
  accounttype: String,
  monthsatbank: String,
  paychecktype: String,
});

module.exports = mongoose.model("Data", dataSchema);
